# Use Nginx
FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy frontend files to nginx folder
COPY index.html /usr/share/nginx/html/
COPY pages /usr/share/nginx/html/pages
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js

# Expose port 80
EXPOSE 80
