pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                echo 'Code cloned from GitHub'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Backend') {
                    sh 'docker build -t food-backend-image .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop food-backend-container || true
                docker rm food-backend-container || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                docker run -d \
                --name food-backend-container \
                -p 5000:5000 \
                food-backend-image
                '''
            }
        }
    }
}
