pipeline {
    agent any

    environment {
        MONGO_URI = credentials('mongo_uri')
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/dishabirje2003/Food-Delivery-Web-App.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Backend') {
                    sh 'docker build -t food-backend-image .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop food-backend-container || true
                docker rm food-backend-container || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                docker run -d \
                --name food-backend-container \
                -p 5000:5000 \
                --env MONGO_URI=$MONGO_URI \
                food-backend-image
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Backend deployed successfully!'
        }
        failure {
            echo '❌ Deployment failed. Check console output for errors.'
        }
    }
}
